#connexion route
connexion:
      path: /connexion
      controller: App\Controller\ConnexionController::connexion

#courrier route
courrier:
      path: /courrier
      controller: App\Controller\CourrierController::courrier

#courrier create route
courrier create:
      path: /courrier/create
      controller: App\Controller\CourrierCreateController::create

#courrier modify route
courrier modify:
      path: /courrier/modify
      controller: App\Controller\CourrierModifyController::modify

#courrier modify route
courrier delete:
      path: /courrier/delete
      controller: App\Controller\CourrierDeleteController::delete

#service route
service:
      path: /service
      controller: App\Controller\ServiceController::service

#service create route
service create:
      path: /service/create
      controller: App\Controller\ServiceCreateController::create

#service modify route
service modify:
      path: /service/modify
      controller: App\Controller\ServiceModifyController::modify

#service delete route
service delete:
      path: /service/delete
      controller: App\Controller\ServiceDeleteController::delete

#information route
information:
      path: /information
      controller: App\Controller\InformationController::information

#information create route
information create:
      path: /information/create
      controller: App\Controller\InformationCreateController::create

#information modify route
information modify:
      path: /information/modify
      controller: App\Controller\InformationModifyController::modify

#information delete route
information delete:
      path: /information/delete
      controller: App\Controller\InformationDeleteController::delete

#administration route
administration:
      path: /administration
      controller: App\Controller\AdministrationController::administration

#administration user route
administration user:
      path: /administration/user
      controller: App\Controller\AdministrationUserController::user

#administration user common route
administration user common:
      path: /administration/user/common
      controller: App\Controller\AdministrationUserCommonController::common

#administration user permissions route
administration user permissions:
      path: /administration/user/permissions
      controller: App\Controller\AdministrationUserPermissionsController::permissions

#administration user delete route
administration user delete:
      path: /administration/user/delete
      controller: App\Controller\AdministrationUserDeleteController::delete

#administration user create route
administration user create:
      path: /administration/user/create
      controller: App\Controller\AdministrationUserCreateController::create

#user logout route
app_logout:
      path: /logout
      methods: GET
