#connexion route
connexion:
      path: /connexion
      controller: App\Controller\ConnexionController::connexion

#courrier route
courrier:
      path: /courrier
      controller: App\Controller\CourrierController::courrier

#service route
service:
      path: /service
      controller: App\Controller\ServiceController::service

#information route
information:
      path: /information
      controller: App\Controller\InformationController::information


#administration route
administration:
      path: /administration
      controller: App\Controller\AdministrationController::administration

#administration user route
administration user:
      path: /administration/user
      controller: App\Controller\AdministrationUserController::user

#administration user common route
administration user common:
      path: /administration/user/common
      controller: App\Controller\AdministrationUserCommonController::common

#administration user permissions route
administration user permissions:
      path: /administration/user/permissions
      controller: App\Controller\AdministrationUserPermissionsController::permissions

#administration user delete route
administration user delete:
      path: /administration/user/delete
      controller: App\Controller\AdministrationUserDeleteController::delete

#administration user create route
administration user create:
      path: /administration/user/create
      controller: App\Controller\AdministrationUserCreateController::create

#connexion:
#      path: /connexion
#      controller: App\Controller\SecurityController::connexion
#      methods: GET|POST
