#connexion route
connexion:
      path: /connexion
      controller: App\Controller\ConnexionController::connexion

#administration route
administration:
      path: /administration
      controller: App\Controller\AdministrationController::administration

#administration user route
administration user:
      path: /administration/user
      controller: App\Controller\AdministrationUserController::user

#courrier route
courrier:
      path: /courrier
      controller: App\Controller\CourrierController::courrier

#service route
service:
      path: /service
      controller: App\Controller\ServiceController::service

#information route
information:
      path: /information
      controller: App\Controller\InformationController::information